require "crystal/system/unix/mach_o"

lib LibC
  fun _dyld_image_count : UInt32
  fun _dyld_get_image_name(image_index : UInt32) : Char*
  fun _dyld_get_image_vmaddr_slide(image_index : UInt32) : Long
end

struct Exception::CallStack
  DEBUG_LINE_STR = "__debug_line_str"
  DEBUG_STR      = "__debug_str"
  DEBUG_LINE     = "__debug_line"
  DEBUG_ABBREV   = "__debug_abbrev"
  DEBUG_INFO     = "__debug_info"

  @@base_address = LibC::Long.new(0)

  protected def self.load_debug_info_impl : Nil
    if dsym = locate_dsym_bundle
      load_base_address
      preload_dwarf_sections(dsym)
    end
  end

  # DWARF uses fixed addresses but Darwin loads executables at a random
  # address, so we must remove the load offset from the IP to match the
  # addresses in DWARF sections.
  #
  # See https://en.wikipedia.org/wiki/Address_space_layout_randomization
  protected def self.decode_address(ip)
    if ip.null?
      ip.address
    else
      ip.address &- @@base_address
    end
  end

  # Searches the companion dSYM bundle with the DWARF sections for the
  # current program as generated by `dsymutil`. It may be a `foo.dwarf` file
  # or within a `foo.dSYM` bundle for a program named `foo`.
  #
  # See <http://wiki.dwarfstd.org/index.php?title=Apple%27s_%22Lazy%22_DWARF_Scheme> for details.
  private def self.locate_dsym_bundle
    return unless path = Process.executable_path

    files = {
      "#{path}.dSYM/Contents/Resources/DWARF/#{File.basename(path)}",
      "#{path}.dwarf",
    }

    files.each do |dwarf_path|
      next unless File.exists?(dwarf_path)

      Crystal::System::MachO.open(path) do |mach_o|
        dsym = Crystal::System::MachO.open(dwarf_path)
        return dsym if dsym.try(&.uuid) == mach_o.uuid
      end
    end
  end

  # Determine the address offset at which the program was loaded at.
  private def self.load_base_address : Nil
    buffer = GC.malloc_atomic(LibC::PATH_MAX).as(UInt8*)
    size = LibC::PATH_MAX.to_u32

    if LibC._NSGetExecutablePath(buffer, pointerof(size)) == -1
      buffer = GC.malloc_atomic(size).as(UInt8*)
      return if LibC._NSGetExecutablePath(buffer, pointerof(size)) == -1
    end

    program = File.realpath(String.new(buffer))

    LibC._dyld_image_count.times do |i|
      if program == File.realpath(String.new(LibC._dyld_get_image_name(i)))
        @@base_address = LibC._dyld_get_image_vmaddr_slide(i)
        return
      end
    end
  end
end
