module Crystal
  module DWARF
    # :nodoc:
    #
    # Standard Line Number opcodes.
    enum LNS : UInt8
      Copy             =  1
      AdvancePc        =  2
      AdvanceLine      =  3
      SetFile          =  4
      SetColumn        =  5
      NegateStmt       =  6
      SetBasicBlock    =  7
      ConstAddPc       =  8
      FixedAdvancePc   =  9
      SetPrologueEnd   = 10
      SetEpilogueBegin = 11
      SetIsa           = 12
    end

    # :nodoc:
    #
    # Extended Line Number opcodes.
    enum LNE : UInt8
      EndSequence      = 1
      SetAddress       = 2
      DefineFile       = 3
      SetDiscriminator = 4
    end

    # DWARF Line Numbers resolver. Supports DWARF versions 2, 3, 4 and 5.
    #
    # Usually located in the `.debug_line` section of ELF executables, or the
    # `__debug_line` section of Mach-O files.
    #
    # The decompressed line number matrix for a whole program is huge, and
    # decoding it eagerly retains a large amount of heap memory that the GC
    # is unlikely to ever return to the OS. This decoder therefore never
    # materializes the matrix: `resolve` streams the statement programs,
    # matching the requested program counters on the fly, and only decodes
    # the directory and file names actually referenced by matched rows.
    #
    # Documentation:
    # - [DWARF2](http://dwarfstd.org/doc/dwarf-2.0.0.pdf) section 6.2
    # - [DWARF3](http://dwarfstd.org/doc/Dwarf3.pdf) section 6.2
    # - [DWARF4](http://dwarfstd.org/doc/DWARF4.pdf) section 6.2
    # - [DWARF5](http://dwarfstd.org/doc/DWARF5.pdf) section 6.2
    struct LineNumbers
      # :nodoc:
      #
      # The state machine registers used to decompress the line number
      # sequences.
      struct Register
        # The Program Counter (PC) value corresponding to a machine instruction
        # generated by the compiler.
        property address : UInt64

        # The index of an operation inside a Very Long Instruction Word (VLIW)
        # instruction. Together with `address` they reference an individual
        # operation.
        property op_index : UInt32

        # Source file for the instruction.
        property file : UInt32

        # Line number within the source file. Starting at 1; the value 0 means
        # that the instruction can't be attributed to any source line.
        property line : UInt32

        # Column number within the source file. Starting at 1; the value 0 means
        # that a statement begins at the "left edge" of the line.
        property column : UInt32

        # Recommended breakpoint location.
        property is_stmt : Bool

        # Indicates that the instruction is the beginning of a basic block.
        property basic_block : Bool

        # Terminates a sequence of lines. Other information in the same row (of
        # the decoded matrix) isn't meaningful.
        property end_sequence : Bool

        # Indicates the instruction is one where execution should be
        # suspended (for an entry breakpoint).
        property prologue_end : Bool

        # Indicates the instruction is one where execution should be
        # suspended (for an exit breakpoint).
        property epilogue_begin : Bool

        # Applicable Instruction Set Architecture for the instruction.
        property isa : UInt32

        # Identifies the block to which the instruction belongs.
        property discriminator : UInt32

        def initialize(@is_stmt)
          @address = 0_u64
          @op_index = 0_u32
          @file = 1_u32
          @line = 1_u32
          @column = 0_u32
          @basic_block = false
          @end_sequence = false
          @prologue_end = false
          @epilogue_begin = false
          @isa = 0_u32
          @discriminator = 0_u32
        end

        def reset
          @basic_block = false
          @prologue_end = false
          @epilogue_begin = false
          @discriminator = 0_u32
        end
      end

      # A program counter matched during the statement program run (phase
      # one), recorded with the raw file name index so the file path can be
      # decoded afterwards (phase two), and only if actually referenced.
      record Match,
        pc_index : Int32,
        file : UInt32,
        line : Int32,
        column : Int32

      @size : Int32

      def initialize(@io : IO::Memory, @base_address : UInt64 = 0_u64, @strings : Strings? = nil, @line_strings : Strings? = nil)
        @size = @io.size
      end

      # Resolves line number information for the given program counters,
      # which must be sorted in ascending order and deduplicated. Yields the
      # index of the program counter within `pcs` along with the source path,
      # line and column. Each pc is yielded at most once; pcs without line
      # number information are not yielded.
      def resolve(pcs : Slice(UInt64), & : Int32, String, Int32, Int32 ->) : Nil
        return if pcs.empty?

        resolved = Bytes.new(pcs.size)
        remaining = pcs.size
        matches = [] of Match

        while @io.pos < @size && remaining > 0
          matches.clear
          unit_end, version, table_pos = scan_unit(pcs, resolved, matches, remaining)

          unless matches.empty?
            remaining -= matches.size
            @io.pos = table_pos
            file_paths = decode_file_paths(version, matches)
            matches.each do |match|
              if path = file_paths.find { |entry| entry[0] == match.file }
                yield match.pc_index, path[1], match.line, match.column
              end
            end
          end

          @io.pos = Math.min(unit_end, @size.to_i64)
        end
      end

      private macro increment_address_and_op_index(operation_advance)
        if maximum_operations_per_instruction == 1
          registers.address += {{operation_advance}} * minimum_instruction_length
        else
          registers.address += minimum_instruction_length *
            ((registers.op_index + {{operation_advance}}) // maximum_operations_per_instruction)
          registers.op_index = (registers.op_index + {{operation_advance}}) % maximum_operations_per_instruction
        end
      end

      # Decodes one line number program unit header and runs its statement
      # program without decoding the directory and file name tables,
      # recording a `Match` for every pc it resolves. Returns the unit end
      # offset, the unit version and the offset of the directory table so
      # file paths for the matches can be decoded afterwards.
      #
      # TODO: support LNE::DefineFile (manually register file, uncommon)
      private def scan_unit(pcs, resolved, matches, max_matches)
        offset = @io.pos.to_i64
        unit_length = @io.read_bytes(UInt32)
        unit_end = offset + unit_length + sizeof(typeof(unit_length))
        version = @io.read_bytes(UInt16)

        if version < 2 || version > 5
          raise "Unknown line table version: #{version}"
        end

        if version >= 5
          _address_size = @io.read_bytes(UInt8).to_i
          _segment_selector_size = @io.read_bytes(UInt8).to_i
        end

        header_length = @io.read_bytes(UInt32) # FIXME: UInt64 for DWARF64 (uncommon)
        program_begin = @io.pos.to_i64 + header_length

        minimum_instruction_length = @io.read_bytes(UInt8).to_i

        if version >= 4
          maximum_operations_per_instruction = @io.read_bytes(UInt8).to_i
        else
          maximum_operations_per_instruction = 1
        end

        if maximum_operations_per_instruction == 0
          raise "Invalid maximum operations per instruction: 0"
        end

        default_is_stmt = @io.read_byte == 1
        line_base = @io.read_bytes(Int8).to_i
        line_range = @io.read_bytes(UInt8).to_i
        if line_range == 0
          raise "Invalid line range: 0"
        end

        opcode_base = @io.read_bytes(UInt8).to_i
        standard_opcode_lengths = uninitialized UInt8[256]
        standard_opcode_lengths[0] = 0_u8
        (1...opcode_base).each do |i|
          standard_opcode_lengths[i] = @io.read_byte.not_nil!
        end

        table_pos = @io.pos

        # the directory and file name tables are skipped here; they are only
        # decoded (in `#decode_file_paths`) when the statement program below
        # resolved one of the requested pcs
        if program_begin < table_pos || program_begin >= unit_end
          return {unit_end, version.to_i, table_pos}
        end
        @io.pos = program_begin

        registers = Register.new(default_is_stmt)
        prev_set = false
        prev_address = 0_u64
        prev_file = 0_u32
        prev_line = 0
        prev_column = 0

        loop do
          break if @io.pos >= unit_end || matches.size >= max_matches

          opcode = @io.read_byte.not_nil!

          emit = false
          if opcode >= opcode_base
            # special opcode
            adjusted_opcode = opcode - opcode_base
            operation_advance = adjusted_opcode // line_range
            increment_address_and_op_index(operation_advance)
            registers.line &+= line_base + (adjusted_opcode % line_range)
            emit = true
          elsif opcode == 0
            # extended opcode
            len = DWARF.read_unsigned_leb128(@io) - 1 # -1 accounts for the opcode
            case LNE.new(@io.read_byte.not_nil!)
            when LNE::EndSequence
              registers.end_sequence = true
              emit = true
            when LNE::SetAddress
              case len
              when 8 then registers.address = @io.read_bytes(UInt64)
              when 4 then registers.address = @io.read_bytes(UInt32).to_u64
              else        @io.skip(len)
              end
              registers.op_index = 0_u32
            when LNE::SetDiscriminator
              registers.discriminator = DWARF.read_unsigned_leb128(@io)
            else
              # skip unsupported opcode
              @io.skip(len)
            end
          else
            case LNS.new(opcode)
            when .copy?
              emit = true
            when .advance_pc?
              operation_advance = DWARF.read_unsigned_leb128(@io)
              increment_address_and_op_index(operation_advance)
            when .advance_line?
              registers.line &+= DWARF.read_signed_leb128(@io)
            when .set_file?
              registers.file = DWARF.read_unsigned_leb128(@io)
            when .set_column?
              registers.column = DWARF.read_unsigned_leb128(@io)
            when .negate_stmt?
              registers.is_stmt = !registers.is_stmt
            when .set_basic_block?
              registers.basic_block = true
            when .const_add_pc?
              adjusted_opcode = 255 - opcode_base
              operation_advance = adjusted_opcode // line_range
              increment_address_and_op_index(operation_advance)
            when .fixed_advance_pc?
              registers.address += @io.read_bytes(UInt16)
              registers.op_index = 0_u32
            when .set_prologue_end?
              registers.prologue_end = true
            when .set_epilogue_begin?
              registers.epilogue_begin = true
            when .set_isa?
              registers.isa = DWARF.read_unsigned_leb128(@io)
            else
              # consume unknown opcode args
              n_args = standard_opcode_lengths[opcode.to_i]
              n_args.times { DWARF.read_unsigned_leb128(@io) }
            end
          end

          if emit
            address = registers.address &+ @base_address
            line = registers.line.to_i32!
            column = registers.column.to_i32!

            # checking is_stmt should be enough to avoid "non statement" operations
            # some of which have confusing line number 0.
            # but some operations within macros seem to be useful and marked as !is_stmt
            # so attempt to include them also
            if registers.is_stmt || (line > 0 && column > 0)
              if prev_set && prev_address < address
                match_range(pcs, resolved, matches, prev_address, address, prev_file, prev_line, prev_column)
              end

              if registers.end_sequence
                match_exact(pcs, resolved, matches, address, registers.file, line, column)
              else
                prev_set = true
                prev_address = address
                prev_file = registers.file
                prev_line = line
                prev_column = column
              end
            elsif registers.end_sequence && prev_set
              # the sequence-terminating row didn't produce a row of its own,
              # so the last emitted row only covers its exact address
              match_exact(pcs, resolved, matches, prev_address, prev_file, prev_line, prev_column)
            end

            if registers.end_sequence
              prev_set = false
              if (@io.pos.to_i64 - offset) < (unit_end - offset)
                registers = Register.new(default_is_stmt)
              else
                break
              end
            else
              registers.reset
            end
          end
        end

        {unit_end, version.to_i, table_pos}
      end

      # Records every yet unresolved pc within `lo...hi` as matching the row
      # `{file, line, column}`.
      private def match_range(pcs, resolved, matches, lo : UInt64, hi : UInt64, file, line, column) : Nil
        index = pcs.bsearch_index { |pc| pc >= lo } || return
        while index < pcs.size && pcs[index] < hi
          if resolved[index] == 0
            resolved[index] = 1_u8
            matches << Match.new(index, file, line, column)
          end
          index += 1
        end
      end

      # Records the pc equal to `address`, if any and yet unresolved, as
      # matching the row `{file, line, column}`.
      private def match_exact(pcs, resolved, matches, address : UInt64, file, line, column) : Nil
        index = pcs.bsearch_index { |pc| pc >= address } || return
        if pcs[index] == address && resolved[index] == 0
          resolved[index] = 1_u8
          matches << Match.new(index, file, line, column)
        end
      end

      # Decodes the directory and file name tables of a unit (the IO must be
      # positioned at their start), materializing only the entries referenced
      # by `matches`. Returns pairs of file name index and full path.
      private def decode_file_paths(version, matches) : Array({UInt32, String})
        if version < 5
          decode_file_paths_v4(matches)
        else
          decode_file_paths_v5(matches)
        end
      end

      private def decode_file_paths_v4(matches) : Array({UInt32, String})
        dir_table_pos = @io.pos
        while skip_string > 0
        end

        # scan the file name table, keeping only the entries some match
        # references
        entries = Array({UInt32, String, UInt32}).new(4)
        index = 0_u32
        loop do
          index &+= 1
          name_pos = @io.pos
          name_length = skip_string
          break if name_length == 0
          dir = DWARF.read_unsigned_leb128(@io)
          DWARF.read_unsigned_leb128(@io) # mtime
          DWARF.read_unsigned_leb128(@io) # bytesize
          if matches.any? { |match| match.file == index }
            entries << {index, string_at(name_pos, name_length), dir}
          end
        end

        # materialize the directories those entries reference
        dirs = Array({UInt32, String}).new(4)
        @io.pos = dir_table_pos
        index = 0_u32
        loop do
          index &+= 1
          name_pos = @io.pos
          name_length = skip_string
          break if name_length == 0
          if entries.any? { |entry| entry[2] == index }
            dirs << {index, string_at(name_pos, name_length)}
          end
        end

        paths = Array({UInt32, String}).new(entries.size + 1)

        # file name index 0 means the information is missing
        if matches.any? { |match| match.file == 0 }
          paths << {0_u32, ""}
        end

        join_file_paths(entries, dirs, paths)
        paths
      end

      private def decode_file_paths_v5(matches) : Array({UInt32, String})
        dir_formats = uninitialized LNCTFormat[255]
        dir_format_count = read_lnct_formats(dir_formats.to_unsafe)
        dir_count = DWARF.read_unsigned_leb128(@io).to_i
        dir_table_pos = @io.pos
        dir_count.times { skip_lnct_entry(dir_formats.to_unsafe, dir_format_count) }

        file_formats = uninitialized LNCTFormat[255]
        file_format_count = read_lnct_formats(file_formats.to_unsafe)
        file_count = DWARF.read_unsigned_leb128(@io).to_i

        # in DWARF 5 file name indexes start at 0
        entries = Array({UInt32, String, UInt32}).new(4)
        file_count.times do |i|
          index = i.to_u32
          if matches.any? { |match| match.file == index }
            path, dir = read_lnct_entry(file_formats.to_unsafe, file_format_count)
            entries << {index, path, dir}
          else
            skip_lnct_entry(file_formats.to_unsafe, file_format_count)
          end
        end

        # materialize the directories those entries reference
        dirs = Array({UInt32, String}).new(4)
        @io.pos = dir_table_pos
        dir_count.times do |i|
          index = i.to_u32
          if entries.any? { |entry| entry[2] == index }
            path, _ = read_lnct_entry(dir_formats.to_unsafe, dir_format_count)
            dirs << {index, path}
          else
            skip_lnct_entry(dir_formats.to_unsafe, dir_format_count)
          end
        end

        paths = Array({UInt32, String}).new(entries.size)
        join_file_paths(entries, dirs, paths)
        paths
      end

      # Joins each file entry with the path of the directory it references,
      # appending the resulting `{file index, full path}` pairs to `paths`.
      private def join_file_paths(entries, dirs, paths) : Nil
        entries.each do |(file_index, name, dir_index)|
          dir = dirs.find { |entry| entry[0] == dir_index }.try(&.[1]) || ""
          name = File.join(dir, name) if name != "" && dir != ""
          paths << {file_index, name}
        end
      end

      record LNCTFormat,
        lnct : LNCT,
        format : FORM

      # :nodoc:
      #
      # DWARF-defined content type codes
      # New in DWARF 5 § 6.2.4.1
      enum LNCT : UInt32
        PATH            = 0x01
        DIRECTORY_INDEX = 0x02
        TIMESTAMP       = 0x03
        SIZE            = 0x04
        MD5             = 0x05
      end

      private def read_lnct_formats(buffer : LNCTFormat*) : Int32
        count = @io.read_byte.not_nil!.to_i
        count.times do |i|
          buffer[i] = LNCTFormat.new(
            lnct: LNCT.new(DWARF.read_unsigned_leb128(@io)),
            format: FORM.new(DWARF.read_unsigned_leb128(@io))
          )
        end
        count
      end

      # Reads an entry of a DWARF 5 directory or file name table, decoding
      # its path and directory index and skipping everything else. Returns
      # the path and the directory index.
      private def read_lnct_entry(formats : LNCTFormat*, format_count : Int32) : {String, UInt32}
        path = ""
        dir = 0_u32

        format_count.times do |i|
          format = formats[i]
          materialize = format.lnct.path?
          str = nil
          val = 0_u64

          case format.format
          when .string?
            if materialize
              str = @io.gets('\0', chomp: true)
            else
              skip_string
            end
          when .line_strp?
            offset = @io.read_bytes(UInt32)
            str = @line_strings.try &.decode(offset) if materialize
          when .strp?
            offset = @io.read_bytes(UInt32)
            str = @strings.try &.decode(offset) if materialize
          when .strp_sup?
            @io.read_bytes(UInt32)
          when .strx?
            # .debug_line.dwo sections not yet supported.
            DWARF.read_unsigned_leb128(@io)
          when .strx1?
            @io.read_bytes(UInt8)
          when .strx2?
            @io.read_bytes(UInt16)
          when .strx3?
            @io.skip 3
          when .strx4?
            @io.read_bytes(UInt32)
          when .data1?
            val = @io.read_bytes(UInt8).to_u64
          when .data2?
            val = @io.read_bytes(UInt16).to_u64
          when .data4?
            val = @io.read_bytes(UInt32).to_u64
          when .data8?
            val = @io.read_bytes(UInt64)
          when .data16?
            @io.skip(16)
          when .block?
            @io.skip(DWARF.read_unsigned_leb128(@io))
          when .udata?
            val = DWARF.read_unsigned_leb128(@io).to_u64
          else
            raise "Unexpected encoding format: #{format.format}"
          end

          case format.lnct
          when .path?
            path = str if str
          when .directory_index?
            dir = val.to_u32!
          else
            # timestamp, size and md5 are irrelevant here
          end
        end

        {path, dir}
      end

      private def skip_lnct_entry(formats : LNCTFormat*, format_count : Int32) : Nil
        format_count.times do |i|
          case format = formats[i].format
          when .string?
            skip_string
          when .line_strp?, .strp?, .strp_sup?
            @io.skip(4)
          when .strx?, .udata?
            DWARF.read_unsigned_leb128(@io)
          when .strx1?, .data1?
            @io.skip(1)
          when .strx2?, .data2?
            @io.skip(2)
          when .strx3?
            @io.skip(3)
          when .strx4?, .data4?
            @io.skip(4)
          when .data8?
            @io.skip(8)
          when .data16?
            @io.skip(16)
          when .block?
            @io.skip(DWARF.read_unsigned_leb128(@io))
          else
            raise "Unexpected encoding format: #{format}"
          end
        end
      end

      # Skips a null-terminated string without materializing it, returning
      # its length.
      private def skip_string : Int32
        slice = @io.to_slice
        pos = @io.pos
        if index = slice.index(0_u8, pos)
          @io.pos = index + 1
          index - pos
        else
          @io.pos = slice.size
          slice.size - pos
        end
      end

      private def string_at(pos : Int32, length : Int32) : String
        String.new(@io.to_slice[pos, length])
      end
    end
  end
end
