blank_issues_enabled: false
contact_links:
  - name: "\U00002753 Crystal Community Forum"
    url: https://forum.crystal-lang.org/c/help-support
    about: Please ask and answer questions here.
  - name: "\U0001F4AC Crystal Community Chat"
    url: https://gitter.im/crystal-lang/crystal
    about: "Official Gitter community chat, also available on IRC: http://webchat.freenode.net/?channels=#crystal-lang"
