module Markdown
  # Markdown rendering options.
  class Options
    # If `true`:
    # - straight quotes will be made curly
    # - `--` will be changed to an en dash
    # - `---` will be changed to an em dash
    # - `...` will be changed to ellipses
    property? smart : Bool

    # If `true`, source position information for block-level elements
    # will be rendered in the data-sourcepos attribute (for HTML)
    property? source_pos : Bool

    # If `true`, raw HTML will not be passed through to HTML output
    # (it will be replaced by comments)
    property? safe : Bool

    # If `true`, code tags generated by code blocks will have a
    # prettyprint class added to them, to be used by
    # [Google code-prettify](https://github.com/google/code-prettify).
    property? prettyprint : Bool

    def initialize(
      @smart = false,
      @source_pos = false,
      @safe = false,
      @prettyprint = false
    )
    end
  end
end
