require "./crystal/annotatable"
require "./crystal/program"
require "./crystal/*"
require "./crystal/diagnostic/syntax_highlighter"
require "./crystal/semantic/*"
require "./crystal/macros/*"
require "./crystal/codegen/*"
