require "spec"
{% unless flag?(:win32) %}
require "./std/**"
{% else %}
# This list gives an overview over which specs are currently working on win32
# and what not.
#
# There are different levels of not-working:
#
# * Specs that error at compile time are completely commented out. This is
# mostly caused by some API not being ported to win32 (either the spec target or
# the spec uses non-ported features).
# * Specs that compile but don't link (at least not on basis of the *Porting to
# Windows* guide) are guarded by the `require_nolink` macro. When passing
#`-Dwin32_nolink` they can be enabled for testing codegen. Most of are just
# caused by missing libraries (libxml2, libyaml, libgmp, libllvm, libz, libssl),
# but there also seem to be some incompatibilities with the existing libraries.
# * Some of the `require_nolink` specs are annotated as `# execution breaks`,
# which means linking is fine but they break the entire spec suite at runtime.

private macro require_nolink(path)
  {% if flag?(:win32_nolink) %}
    require {{ path }}
  {% end %}
end

require_nolink "./std/adler32_spec.cr"
require "./std/array_spec.cr"
require "./std/atomic_spec.cr"
require "./std/base64_spec.cr"
# require "./std/benchmark_spec.cr"
require_nolink "./std/big/**"
require "./std/bit_array_spec.cr"
require "./std/bool_spec.cr"
require "./std/box_spec.cr"
# require "./std/callstack_spec.cr"
# require "./std/channel_spec.cr"
require "./std/char/**"
require "./std/char_spec.cr"
require "./std/class_spec.cr"
require "./std/colorize_spec.cr"
require_nolink "./std/comparable_spec.cr" # execution breaks
require_nolink "./std/complex_spec.cr"
require_nolink "./std/concurrent/**" # execution breaks
require "./std/concurrent_spec.cr"
require_nolink "./std/crc32_spec.cr"
require_nolink "./std/crypto/**"
require_nolink "./std/crystal/**"
require "./std/csv/**"
require "./std/deque_spec.cr"
require_nolink "./std/digest/**"
require "./std/dir_spec.cr"
require "./std/double_spec.cr"
require "./std/ecr/**"
require "./std/enumerable_spec.cr"
require "./std/enum_spec.cr"
require "./std/env_spec.cr"
require "./std/exception_spec.cr"
# require "./std/file/**"
# require "./std/file_spec.cr"
# require "./std/file_utils_spec.cr"
require_nolink "./std/flate/**"
require "./std/float_printer/**"
require_nolink "./std/float_spec.cr"
require "./std/gc_spec.cr"
require_nolink "./std/gzip/**"
require "./std/hash_spec.cr"
require "./std/html_spec.cr"
# require "./std/http/**"
require "./std/humanize_spec.cr"
require "./std/indexable_spec.cr"
require "./std/ini_spec.cr"
require_nolink "./std/int_spec.cr"
# require "./std/io/**"
require "./std/iterator_spec.cr"
require_nolink "./std/json/**"
# require "./std/kernel_spec.cr"
require "./std/levenshtein_spec.cr"
require_nolink "./std/llvm/**"
# require "./std/logger_spec.cr"
require "./std/match_data_spec.cr"
require_nolink "./std/math_spec.cr"
# require "./std/mime/**"
require "./std/mime_spec.cr"
# require "./std/mutex_spec.cr"
require "./std/named_tuple_spec.cr"
require_nolink "./std/number_spec.cr"
# require "./std/oauth/**"
# require "./std/oauth2/**"
require "./std/object_spec.cr"
# require "./std/openssl/**"
require "./std/option_parser_spec.cr"
require "./std/path_spec.cr"
require "./std/pointer_spec.cr"
require "./std/pp_spec.cr"
require "./std/pretty_print_spec.cr"
# require "./std/process_spec.cr"
require "./std/proc_spec.cr"
require "./std/raise_spec.cr"
require "./std/random/**"
require_nolink "./std/random_spec.cr"
require_nolink "./std/range_spec.cr"
require "./std/record_spec.cr"
require "./std/reference_spec.cr"
require "./std/regex_spec.cr"
require "./std/semantic_version_spec.cr"
require "./std/set_spec.cr"
# require "./std/signal_spec.cr"
require "./std/slice_spec.cr"
# require "./std/socket/**"
require "./std/spec/context_spec.cr"
require "./std/spec/expectations_spec.cr"
require "./std/spec/filters_spec.cr"
require_nolink "./std/spec/junit_formatter_spec.cr"
require "./std/spec/tap_formatter_spec.cr"
require "./std/spec_spec.cr"
require "./std/static_array_spec.cr"
require "./std/string/**"
require "./std/string_builder_spec.cr"
require "./std/string_pool_spec.cr"
require "./std/string_scanner_spec.cr"
# require "./std/string_spec.cr"
require_nolink "./std/struct_spec.cr"
require "./std/symbol_spec.cr"
# require "./std/system/**"
# require "./std/system_spec.cr"
# require "./std/thread/**"
# require "./std/thread_spec.cr"
require "./std/time/**"
require "./std/tuple_spec.cr"
require "./std/uint_spec.cr"
require "./std/uri/**"
require "./std/uri_spec.cr"
require "./std/uuid_spec.cr"
require "./std/weak_ref_spec.cr"
require_nolink "./std/xml/**"
require_nolink "./std/yaml/**"
require_nolink "./std/zip/**"
require_nolink "./std/zlib/**"
{% end %}
