require "./dwarf/**"

# :nodoc:
module Crystal::DWARF
  DW_UT_compile       = 0x01
  DW_UT_type          = 0x02
  DW_UT_partial       = 0x03
  DW_UT_skeleton      = 0x04
  DW_UT_split_compile = 0x05
  DW_UT_split_type    = 0x06

  DW_TAG_array_type               = 0x01
  DW_TAG_class_type               = 0x02
  DW_TAG_entry_point              = 0x03
  DW_TAG_enumeration_type         = 0x04
  DW_TAG_formal_parameter         = 0x05
  DW_TAG_imported_declaration     = 0x08
  DW_TAG_label                    = 0x0a
  DW_TAG_lexical_block            = 0x0b
  DW_TAG_member                   = 0x0d
  DW_TAG_pointer_type             = 0x0f
  DW_TAG_reference_type           = 0x10
  DW_TAG_compile_unit             = 0x11
  DW_TAG_string_type              = 0x12
  DW_TAG_structure_type           = 0x13
  DW_TAG_subroutine_type          = 0x15
  DW_TAG_typedef                  = 0x16
  DW_TAG_union_type               = 0x17
  DW_TAG_unspecified_parameters   = 0x18
  DW_TAG_variant                  = 0x19
  DW_TAG_common_block             = 0x1a
  DW_TAG_common_inclusion         = 0x1b
  DW_TAG_inheritance              = 0x1c
  DW_TAG_inlined_subroutine       = 0x1d
  DW_TAG_module                   = 0x1e
  DW_TAG_ptr_to_member_type       = 0x1f
  DW_TAG_set_type                 = 0x20
  DW_TAG_subrange_type            = 0x21
  DW_TAG_with_stmt                = 0x22
  DW_TAG_access_declaration       = 0x23
  DW_TAG_base_type                = 0x24
  DW_TAG_catch_block              = 0x25
  DW_TAG_const_type               = 0x26
  DW_TAG_constant                 = 0x27
  DW_TAG_enumerator               = 0x28
  DW_TAG_file_type                = 0x29
  DW_TAG_friend                   = 0x2a
  DW_TAG_namelist                 = 0x2b
  DW_TAG_namelist_item            = 0x2c
  DW_TAG_packed_type              = 0x2d
  DW_TAG_subprogram               = 0x2e
  DW_TAG_template_type_parameter  = 0x2f
  DW_TAG_template_value_parameter = 0x30
  DW_TAG_thrown_type              = 0x31
  DW_TAG_try_block                = 0x32
  DW_TAG_variant_part             = 0x33
  DW_TAG_variable                 = 0x34
  DW_TAG_volatile_type            = 0x35
  DW_TAG_dwarf_procedure          = 0x36
  DW_TAG_restrict_type            = 0x37
  DW_TAG_interface_type           = 0x38
  DW_TAG_namespace                = 0x39
  DW_TAG_imported_module          = 0x3a
  DW_TAG_unspecified_type         = 0x3b
  DW_TAG_partial_unit             = 0x3c
  DW_TAG_imported_unit            = 0x3d
  DW_TAG_condition                = 0x3f
  DW_TAG_shared_type              = 0x40
  DW_TAG_type_unit                = 0x41
  DW_TAG_rvalue_reference_type    = 0x42
  DW_TAG_template_alias           = 0x43
  DW_TAG_coarray_type             = 0x44
  DW_TAG_generic_subrange         = 0x45
  DW_TAG_dynamic_type             = 0x46
  DW_TAG_atomic_type              = 0x47
  DW_TAG_call_site                = 0x48
  DW_TAG_call_siteparameter       = 0x49
  DW_TAG_skeleton_unit            = 0x4a
  DW_TAG_immutable_type           = 0x4b

  DW_AT_sibling                 = 0x01 # reference
  DW_AT_location                = 0x02 # exprloc, loclistptr
  DW_AT_name                    = 0x03 # string
  DW_AT_ordering                = 0x09 # constant
  DW_AT_byte_size               = 0x0b # constant, exprloc, reference
  DW_AT_bit_offset              = 0x0c # constant, exprloc, reference
  DW_AT_bit_size                = 0x0d # constant, exprloc, reference
  DW_AT_stmt_list               = 0x10 # lineptr
  DW_AT_low_pc                  = 0x11 # address
  DW_AT_high_pc                 = 0x12 # address, constant
  DW_AT_language                = 0x13 # constant
  DW_AT_discr                   = 0x15 # reference
  DW_AT_discr_value             = 0x16 # constant
  DW_AT_visibility              = 0x17 # constant
  DW_AT_import                  = 0x18 # reference
  DW_AT_string_length           = 0x19 # exprloc, loclistptr
  DW_AT_common_reference        = 0x1a # reference
  DW_AT_comp_dir                = 0x1b # string
  DW_AT_const_value             = 0x1c # block, constant, string
  DW_AT_containing_type         = 0x1d # reference
  DW_AT_default_value           = 0x1e # reference
  DW_AT_inline                  = 0x20 # constant
  DW_AT_is_optional             = 0x21 # flag
  DW_AT_lower_bound             = 0x22 # constant, exprloc, reference
  DW_AT_producer                = 0x25 # string
  DW_AT_prototyped              = 0x27 # flag
  DW_AT_return_addr             = 0x2a # exprloc, loclistptr
  DW_AT_start_scope             = 0x2c # constant, rangelistptr
  DW_AT_bit_stride              = 0x2e # constant, exprloc, reference
  DW_AT_upper_bound             = 0x2f # constant, exprloc, reference
  DW_AT_abstract_origin         = 0x31 # reference
  DW_AT_accessibility           = 0x32 # constant
  DW_AT_address_class           = 0x33 # constant
  DW_AT_artificial              = 0x34 # flag
  DW_AT_base_types              = 0x35 # reference
  DW_AT_calling_convention      = 0x36 # constant
  DW_AT_count                   = 0x37 # constant, exprloc, reference
  DW_AT_data_member_location    = 0x38 # constant, exprloc, loclistptr
  DW_AT_decl_column             = 0x39 # constant
  DW_AT_decl_file               = 0x3a # constant
  DW_AT_decl_line               = 0x3b # constant
  DW_AT_declaration             = 0x3c # flag
  DW_AT_discr_list              = 0x3d # block
  DW_AT_encoding                = 0x3e # constant
  DW_AT_external                = 0x3f # flag
  DW_AT_frame_base              = 0x40 # exprloc, loclistptr
  DW_AT_friend                  = 0x41 # reference
  DW_AT_identifier_case         = 0x42 # constant
  DW_AT_macro_info              = 0x43 # macptr
  DW_AT_namelist_item           = 0x44 # reference
  DW_AT_priority                = 0x45 # reference
  DW_AT_segment                 = 0x46 # exprloc, loclistptr
  DW_AT_specification           = 0x47 # reference
  DW_AT_static_link             = 0x48 # exprloc, loclistptr
  DW_AT_type                    = 0x49 # reference
  DW_AT_use_location            = 0x4a # exprloc, loclistptr
  DW_AT_variable_parameter      = 0x4b # flag
  DW_AT_virtuality              = 0x4c # constant
  DW_AT_vtable_elem_location    = 0x4d # exprloc, loclistptr
  DW_AT_allocated               = 0x4e # constant, exprloc, reference
  DW_AT_associated              = 0x4f # constant, exprloc, reference
  DW_AT_data_location           = 0x50 # exprloc
  DW_AT_byte_stride             = 0x51 # constant, exprloc, reference
  DW_AT_entry_pc                = 0x52 # address
  DW_AT_use_UTF8                = 0x53 # flag
  DW_AT_extension               = 0x54 # reference
  DW_AT_ranges                  = 0x55 # rangelistptr
  DW_AT_trampoline              = 0x56 # address, flag, reference, string
  DW_AT_call_column             = 0x57 # constant
  DW_AT_call_file               = 0x58 # constant
  DW_AT_call_line               = 0x59 # constant
  DW_AT_description             = 0x5a # string
  DW_AT_binary_scale            = 0x5b # constant
  DW_AT_decimal_scale           = 0x5c # constant
  DW_AT_small                   = 0x5d # reference
  DW_AT_decimal_sign            = 0x5e # constant
  DW_AT_digit_count             = 0x5f # constant
  DW_AT_picture_string          = 0x60 # string
  DW_AT_mutable                 = 0x61 # flag
  DW_AT_threads_scaled          = 0x62 # flag
  DW_AT_explicit                = 0x63 # flag
  DW_AT_object_pointer          = 0x64 # reference
  DW_AT_endianity               = 0x65 # constant
  DW_AT_elemental               = 0x66 # flag
  DW_AT_pure                    = 0x67 # flag
  DW_AT_recursive               = 0x68 # flag
  DW_AT_signature               = 0x69 # reference
  DW_AT_main_subprogram         = 0x6a # flag
  DW_AT_data_bit_offset         = 0x6b # constant
  DW_AT_const_expr              = 0x6c # flag
  DW_AT_enum_class              = 0x6d # flag
  DW_AT_linkage_name            = 0x6e # string
  DW_AT_string_length_bit_size  = 0x6f # constant
  DW_AT_string_length_byte_size = 0x70 # constant
  DW_AT_rank                    = 0x71 # constant, exprloc
  DW_AT_str_offsets_base        = 0x72 # stroffsetsptr
  DW_AT_addr_base               = 0x73 # addrptr
  DW_AT_rnglists_base           = 0x74 # rnglistsptr
  DW_AT_dwo_name                = 0x76 # string
  DW_AT_reference               = 0x77 # flag
  DW_AT_rvalue_reference        = 0x78 # flag
  DW_AT_macros                  = 0x79 # macptr
  DW_AT_call_all_calls          = 0x7a # flag
  DW_AT_call_all_source_calls   = 0x7b # flag
  DW_AT_call_all_tail_calls     = 0x7c # flag
  DW_AT_call_return_pc          = 0x7d # address
  DW_AT_call_value              = 0x7e # exprloc
  DW_AT_call_origin             = 0x7f # exprloc
  DW_AT_call_parameter          = 0x80 # reference
  DW_AT_call_pc                 = 0x81 # address
  DW_AT_call_tail_call          = 0x82 # flag
  DW_AT_call_target             = 0x83 # exprloc
  DW_AT_call_target_clobbered   = 0x84 # exprloc
  DW_AT_call_data_location      = 0x85 # exprloc
  DW_AT_call_data_value         = 0x86 # exprloc
  DW_AT_noreturn                = 0x87 # flag
  DW_AT_alignment               = 0x88 # constant
  DW_AT_export_symbols          = 0x89 # flag
  DW_AT_deleted                 = 0x8a # flag
  DW_AT_defaulted               = 0x8b # constant
  DW_AT_loclists_base           = 0x8c # loclistsptr

  DW_FORM_addr           = 0x01_u32 # address
  DW_FORM_block2         = 0x03_u32 # block
  DW_FORM_block4         = 0x04_u32 # block
  DW_FORM_data2          = 0x05_u32 # constant
  DW_FORM_data4          = 0x06_u32 # constant
  DW_FORM_data8          = 0x07_u32 # constant
  DW_FORM_string         = 0x08_u32 # string
  DW_FORM_block          = 0x09_u32 # block
  DW_FORM_block1         = 0x0a_u32 # block
  DW_FORM_data1          = 0x0b_u32 # constant
  DW_FORM_flag           = 0x0c_u32 # flag
  DW_FORM_sdata          = 0x0d_u32 # constant
  DW_FORM_strp           = 0x0e_u32 # string
  DW_FORM_udata          = 0x0f_u32 # constant
  DW_FORM_ref_addr       = 0x10_u32 # reference
  DW_FORM_ref1           = 0x11_u32 # reference
  DW_FORM_ref2           = 0x12_u32 # reference
  DW_FORM_ref4           = 0x13_u32 # reference
  DW_FORM_ref8           = 0x14_u32 # reference
  DW_FORM_ref_udata      = 0x15_u32 # reference
  DW_FORM_indirect       = 0x16_u32 # (see Section 7.5.3)
  DW_FORM_sec_offset     = 0x17_u32 # lineptr, loclistptr, macptr, rangelistptr
  DW_FORM_exprloc        = 0x18_u32 # exprloc
  DW_FORM_flag_present   = 0x19_u32 # flag
  DW_FORM_strx           = 0x1a_u32 # string
  DW_FORM_addrx          = 0x1b_u32 # address
  DW_FORM_ref_sup4       = 0x1c_u32 # reference
  DW_FORM_strp_sup       = 0x1d_u32 # string
  DW_FORM_data16         = 0x1e_u32 # constant
  DW_FORM_line_strp      = 0x1f_u32 # string
  DW_FORM_ref_sig8       = 0x20_u32 # reference
  DW_FORM_implicit_const = 0x21_u32 # constant
  DW_FORM_loclistx       = 0x22_u32 # loclist
  DW_FORM_rnglistx       = 0x23_u32 # rnglist
  DW_FORM_ref_sup8       = 0x24_u32 # reference
  DW_FORM_strx1          = 0x25_u32 # string
  DW_FORM_strx2          = 0x26_u32 # string
  DW_FORM_strx3          = 0x27_u32 # string
  DW_FORM_strx4          = 0x28_u32 # string
  DW_FORM_addrx1         = 0x29_u32 # address
  DW_FORM_addrx2         = 0x2a_u32 # address
  DW_FORM_addrx3         = 0x2b_u32 # address
  DW_FORM_addrx4         = 0x2c_u32 # address

  DW_FORM_GNU_addr_index = 0x1f01_u32
  DW_FORM_GNU_str_index  = 0x1f02_u32
  DW_FORM_GNU_ref_alt    = 0x1f20_u32
  DW_FORM_GNU_strp_alt   = 0x1f21_u32

  DW_LNS_copy               =  1
  DW_LNS_advance_pc         =  2
  DW_LNS_advance_line       =  3
  DW_LNS_set_file           =  4
  DW_LNS_set_column         =  5
  DW_LNS_negate_stmt        =  6
  DW_LNS_set_basic_block    =  7
  DW_LNS_const_add_pc       =  8
  DW_LNS_fixed_advance_pc   =  9
  DW_LNS_set_prologue_end   = 10
  DW_LNS_set_epilogue_begin = 11
  DW_LNS_set_isa            = 12

  DW_LNE_end_sequence      = 1
  DW_LNE_set_address       = 2
  DW_LNE_define_file       = 3
  DW_LNE_set_discriminator = 4

  DW_LNCT_path            = 0x01_u32
  DW_LNCT_directory_index = 0x02_u32
  DW_LNCT_timestamp       = 0x03_u32
  DW_LNCT_size            = 0x04_u32
  DW_LNCT_md5             = 0x05_u32

  class Error < Exception
  end
end
