name: Update devenv

on:
  schedule:
    - cron: "0 3 * * 2" # Weekly on Tuesdays
  push:
    branches:
      - master
    paths:
      - '.github/workflows/update-devenv.yml'
  workflow_dispatch:

permissions: {}

jobs:
  update-devenv:
    if: github.repository == 'crystal-lang/crystal'
    runs-on: ubuntu-latest
    environment: github-write

    steps:
      - name: Download source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: master
          persist-credentials: false

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: Update devenv.lock
        run: devenv update

      - name: Check for changes
        id: changes
        run: |
          git add devenv.lock
          if git diff --cached --quiet; then
            echo "changed=false" >>"$GITHUB_OUTPUT"
          else
            echo "changed=true" >>"$GITHUB_OUTPUT"
          fi

      - name: Create PR
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          commit-message: "Update `devenv.lock`"
          title: "Update `devenv.lock`"
          body: ""
          labels: "topic:infrastructure"
          branch: infra/update-devenv
          delete-branch: true
          token: ${{ secrets.CRYSBOT_WRITE_PAT }}
