name: Update devenv

on:
  schedule:
    - cron: "0 3 * * 2" # Weekly on Tuesdays
  push:
    branches:
      - master
    paths:
      - '.github/workflows/update-devenv.yml'
  workflow_dispatch:

permissions: {}

jobs:
  update-devenv:
    if: github.repository == 'crystal-lang/crystal'
    runs-on: ubuntu-latest
    environment: github-write

    steps:
      - name: Download source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: master
          persist-credentials: false

      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: Update devenv.lock
        run: devenv update

      - name: Check for changes
        id: changes
        run: |
          git add devenv.lock
          if git diff --cached --quiet; then
            echo "changed=false" >>"$GITHUB_OUTPUT"
          else
            echo "changed=true" >>"$GITHUB_OUTPUT"
          fi

      - name: Create PR
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          commit-message: "Update `devenv.lock`"
          title: "Update `devenv.lock`"
          body: ""
          labels: "topic:infrastructure"
          branch: infra/update-devenv
          delete-branch: true
          token: ${{ secrets.CRYSBOT_WRITE_PAT }}
