name: Windows CI

on: [push, pull_request, workflow_dispatch]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  x86_64-msvc:
    name: x64 MSVC
    uses: ./.github/workflows/win_steps.yml
    with:
      arch: x86_64
      runs-on: windows-2025-vs2026
      llvm_version: "20.1.7"
      llvm_targets: "X86;AArch64"
      llvm_ldflags: "psapi.lib shell32.lib ole32.lib uuid.lib advapi32.lib ws2_32.lib ntdll.lib"

  aarch64-msvc:
    name: ARM64 MSVC
    uses: ./.github/workflows/win_steps.yml
    with:
      arch: aarch64
      runs-on: windows-11-vs2026-arm
      llvm_version: "22.1.8"
      llvm_targets: "X86;AArch64"
      llvm_ldflags: "psapi.lib shell32.lib ole32.lib uuid.lib advapi32.lib ws2_32.lib ntdll.lib"
