name: Windows CI

on: [push, pull_request, workflow_dispatch]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  SPEC_SPLIT_DOTS: 160
  CI_LLVM_VERSION: "23.1.0"
  CI_LLVM_TARGETS: "X86,AArch64"
  CI_LLVM_LDFLAGS: "psapi.lib shell32.lib ole32.lib uuid.lib advapi32.lib ws2_32.lib ntdll.lib"

jobs:
  x86_64-windows-deps:
    name: Build dependencies
    uses: ./.github/workflows/win_build_libs.yml
    with:
      arch: x86_64
      runs-on: windows-2025-vs2026
      llvm_version: "23.1.0"
      llvm_targets: "X86;AArch64"

  x86_64-windows-release:
    needs: [x86_64-windows-deps]
    uses: ./.github/workflows/win_build_portable.yml
    with:
      release: true
      llvm_version: "23.1.0"
      llvm_targets: "X86;AArch64"
      llvm_ldflags: "psapi.lib shell32.lib ole32.lib uuid.lib advapi32.lib ws2_32.lib ntdll.lib"

  x86_64-windows-test:
    runs-on: windows-2025-vs2026
    needs: [x86_64-windows-release]
    steps:
      - name: Disable CRLF line ending substitution
        run: |
          git config --global core.autocrlf false

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

      - name: Download Crystal source
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Download Crystal executable
        uses: actions/download-artifact@v8
        with:
          name: crystal
          path: build

      - name: Set up environment
        run: |
          Add-Content $env:GITHUB_PATH "$(pwd)\build"
          Add-Content $env:GITHUB_ENV "CRYSTAL_SPEC_COMPILER_BIN=$(pwd)\build\crystal.exe"
          Add-Content $env:GITHUB_ENV "LLVM_VERSION=${{ env.CI_LLVM_VERSION }}"
          Add-Content $env:GITHUB_ENV "LLVM_TARGETS=${{ env.CI_LLVM_TARGETS }}"
          Add-Content $env:GITHUB_ENV "LLVM_LDFLAGS=${{ env.CI_LLVM_LDFLAGS }}"

      - name: Run stdlib specs
        run: make -f Makefile.win std_spec

      - name: Run compiler specs
        run: make -f Makefile.win compiler_spec

      - name: Run interpreter specs
        run: make -f Makefile.win interpreter_spec

      - name: Run primitives specs
        run: make -f Makefile.win -o .build\crystal.exe primitives_spec # we know the compiler is fresh; do not rebuild it here

      - name: Run CLI specs
        run: make -f Makefile.win cli_spec

      - name: Build samples
        run: make -f Makefile.win samples

  test-std:
    runs-on: windows-2025-vs2026
    needs: [x86_64-windows-release]
    strategy:
      fail-fast: false
      matrix:
        opts:
          - flags: "-Dwithout_mt"
          - workers: 4 # execution_context: parallel

    steps:
      - name: Disable CRLF line ending substitution
        run: git config --global core.autocrlf false

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

      - name: Download Crystal source
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Download Crystal executable
        uses: actions/download-artifact@v8
        with:
          name: crystal
          path: build

      - name: Set up environment
        run: |
          Add-Content $env:GITHUB_PATH "$(pwd)\build"
          Add-Content $env:GITHUB_ENV "CRYSTAL_SPEC_COMPILER_BIN=$(pwd)\build\crystal.exe"
          Add-Content $env:GITHUB_ENV "LLVM_VERSION=${{ env.CI_LLVM_VERSION }}"
          Add-Content $env:GITHUB_ENV "LLVM_TARGETS=${{ env.CI_LLVM_TARGETS }}"
          Add-Content $env:GITHUB_ENV "LLVM_LDFLAGS=${{ env.CI_LLVM_LDFLAGS }}"

      - name: Test
        run: make -f Makefile.win std_spec FLAGS="${{ matrix.opts.flags || '' }}"
        env:
          CRYSTAL_WORKERS: ${{ matrix.opts.workers || 1 }}

  x86_64-windows-test-interpreter:
    runs-on: windows-2025-vs2026
    needs: [x86_64-windows-release]
    steps:
      - name: Disable CRLF line ending substitution
        run: |
          git config --global core.autocrlf false

      - name: Download Crystal source
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Download Crystal executable
        uses: actions/download-artifact@v8
        with:
          name: crystal
          path: build

      - name: Set up environment
        run: |
          Add-Content $env:GITHUB_PATH "$(pwd)\build"
          Add-Content $env:GITHUB_ENV "CRYSTAL_SPEC_COMPILER_BIN=$(pwd)\build\crystal.exe"
          Add-Content $env:GITHUB_ENV "LLVM_VERSION=${{ env.CI_LLVM_VERSION }}"
          Add-Content $env:GITHUB_ENV "LLVM_TARGETS=${{ env.CI_LLVM_TARGETS }}"
          Add-Content $env:GITHUB_ENV "LLVM_LDFLAGS=${{ env.CI_LLVM_LDFLAGS }}"

      - name: Build crystal-pu
        run: make -f Makefile.win build\crystal-pu.exe O=build

      - name: Run stdlib specs with interpreter
        run: bin\crystal i spec\std_spec.cr

      - name: Run primitives specs with interpreter
        run: bin\crystal i spec\primitives_spec.cr

  x86_64-windows-installer:
    if: github.repository_owner == 'crystal-lang' && (startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/ci/'))
    runs-on: windows-2025-vs2026
    needs: [x86_64-windows-release]
    steps:
      - name: Disable CRLF line ending substitution
        run: |
          git config --global core.autocrlf false

      - name: Download Crystal source
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Download Crystal executable
        uses: actions/download-artifact@v8
        with:
          name: crystal
          path: etc/win-ci/portable

      - name: Set up Inno Setup
        run: |
          Invoke-WebRequest -Uri https://github.com/jrsoftware/issrc/releases/download/is-7_0_2/innosetup-7.0.2-x64.exe -OutFile C:\is.exe
          C:\is.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART

      - name: Set up environment
        run: |
          Add-Content $env:GITHUB_PATH "$(pwd)\etc\win-ci\portable"
          Add-Content $env:GITHUB_ENV "LLVM_VERSION=${{ env.CI_LLVM_VERSION }}"
          Add-Content $env:GITHUB_ENV "LLVM_TARGETS=${{ env.CI_LLVM_TARGETS }}"
          Add-Content $env:GITHUB_ENV "LLVM_LDFLAGS=${{ env.CI_LLVM_LDFLAGS }}"

      - name: Build docs
        run: make -f Makefile.win install_docs prefix=etc\win-ci\portable

      - name: Build installer
        working-directory: ./etc/win-ci
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" crystal.iss

      - name: Upload Crystal installer
        uses: actions/upload-artifact@v7
        with:
          name: crystal-installer
          path: etc/win-ci/Output/crystal-setup.exe
